python -m data_handling.convert_concept_midis_to_npy --concept_name alberti_bass
python -m data_handling.convert_concept_midis_to_npy --concept_name difficult_pieces
python -m data_handling.convert_concept_midis_to_npy --concept_name contrapuntal_texture
python -m data_handling.convert_concept_midis_to_npy --concept_name random_datasets/random_dataset0
python -m data_handling.convert_concept_midis_to_npy --concept_name random_datasets/random_dataset1
python -m data_handling.convert_concept_midis_to_npy --concept_name random_datasets/random_dataset2
python -m data_handling.convert_concept_midis_to_npy --concept_name random_datasets/random_dataset3
python -m data_handling.convert_concept_midis_to_npy --concept_name random_datasets/random_dataset4
python -m data_handling.convert_concept_midis_to_npy --concept_name random_datasets/random_dataset5
python -m data_handling.convert_concept_midis_to_npy --concept_name random_datasets/random_dataset6
python -m data_handling.convert_concept_midis_to_npy --concept_name random_datasets/random_dataset7
python -m data_handling.convert_concept_midis_to_npy --concept_name random_datasets/random_dataset8
python -m data_handling.convert_concept_midis_to_npy --concept_name random_datasets/random_dataset9
